# Generated by Django 5.1.4 on 2024-12-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='https://via.placeholder.com/150', upload_to='post_images/'),
        ),
    ]
