# Generated by Django 5.1.4 on 2025-02-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff_requested',
            field=models.BooleanField(default=False),
        ),
    ]
