# Generated by Django 5.1.4 on 2025-02-17 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_is_staff_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff_requested',
        ),
    ]
